name: coleta_gps
description: "Aplicativo Rota Limpa"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Google Maps e localização
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2

  # Armazenamento local
  shared_preferences: ^2.5.3

  # Firebase - versões compatíveis com Flutter/Dart do FlutLab
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true