// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdtzAe8pDKjBJ73jbu5Sd4_02nWuh1m5c',
    appId: '1:28747625167:web:0c118781a33c65d8b4fdba',
    messagingSenderId: '28747625167',
    projectId: 'rota-limpa-gps',
    authDomain: 'rota-limpa-gps.firebaseapp.com',
    storageBucket: 'rota-limpa-gps.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedjeDsdM09l8AKSq2nzdVw6_2k66xxJU',
    appId: '1:28747625167:android:6e8b4a07b3e89987b4fdba',
    messagingSenderId: '28747625167',
    projectId: 'rota-limpa-gps',
    storageBucket: 'rota-limpa-gps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOBjSM3e8oYJBavlwJEXs2JJXq9Co6C7c',
    appId: '1:28747625167:ios:08ecc4c940dfa8a6b4fdba',
    messagingSenderId: '28747625167',
    projectId: 'rota-limpa-gps',
    storageBucket: 'rota-limpa-gps.firebasestorage.app',
    iosBundleId: 'com.example.coletaGps',
  );
}
